- subject-chart.html
- mermaid.js라이브러리를 이용하여
- 1학년부터 4학년까지 과목이수체계도를 구현했습니다.
- 일반선택은 배경색상 흰색,
- 전공기초(필수)는 기본 컬러(보라색),
- 공통권장 전공은 노란색으로 지정했습니다.
> mermaid.js를 이용하여 과목이수체계도를 구현했습니다.

- README.md
- js/Show.html
#29 이후에 작성된 추가 PR입니다.
#34 와 #35 를 둘다 섞어보았습니다.
위 사진과 같이 과목명 과 파일 선택 기능 버튼이 추가되었습니다.
파일을 고르고 선택하면
파일의 이름을 불러와 과목명에 이름을 출력합니다.
현재 기능에는 이름만 출력하는 기능을 가지고 있습니다.
실제 데이터를 뽑아와 구현하는 코드는 아직 구현되어 있지 않아 여기까지만 만들었습니다.
(json 파일을 로드하여 출력하는 코드가 없습니다.)
> 파일 선택 & Course Flow Chart Title 추가하였습니다.

- README.md
#8 
Readme.md에 Live Server 사용법을 이미지와 함께 추가하였습니다.
> Live Server 사용법 추가

- Show.html
- css/search.css
> show.html 검색 기능 추가

- subject-chart.html
CSS 스타일 시트가 연결 안 되어 있어 연결했습니다.
> subject_chart.css 연결

- subject-chart.html
학과 홈페이지의 이수체계도를 참고하며 수정했습니다.
모바일 프로그래밍의 노드 선 색상이 blue여서 방금 수정한 파이썬 프로그래밍 -> 객체 지향 프로그래밍의 노드 선 색상을 blue로 수정했습니다.
> 파이썬 프로그래밍이 객체지향 프로그래밍을 향해야하는데 이산구조가 향하고 있어서 노드의 방향을 수정했습니다.

- README.md
README에 파이썬 웹서버 설치 명령어를 추가하였습니다.
> README에 파이썬 웹서버 설치 명령어를 추가

- README.md
파이썬에서 웹서버를 띄우는 방법을 찾아 README에 업로드 하였습니다
> README에 파이썬에서 웹서버를 띄우는 방법을 업로드했습니다.(저보다 먼저올리신 Pull에 더 추가사항을 입력했습니다)

- subject-chart.html
subject-chart.html의 272번째 줄의 addEventListener 메소르들 호출하려고 할 때 null 값을 참조하고 있어 생긴 오류 수정
> subject-chart.html Cannot read properties of null 오류 수정

- css/style.css
- index.html
> index.html 대문에 우리학교 사진을 삽입하고 버튼을 깔끔하게  화면 중앙에 세로로 정렬시켰습니다. 

- README.md
> 파이썬에서 웹서버를 띄우는방법에서 추가옵션에서 코드가 틀려 수정합니다

- js/main.js
> Show.html 그래프 x축 중앙 정렬 했습니다.

- subject-chart.html
#173
검색어가 페이지에 포함되어 있는지 확인하고, 포함되어 있다면 계속 순환 검색을 반복하도록 했습니다.
> 검색 기능 오류 알림창 수정

- index.html
#174 
에서 언급된 글자에 페이지 이동이 가능하게 설정되어있고, 사실상 버튼에 페이지 이동이 불가능한 문제를
글자와 버튼을 하나로 묶어 간단하게 해결하였습니다.
> 인덱스 메인화면의 버튼 인식 문제 해결

- subject-chart.html
> 스크롤 기능 추가(재업로드)

- subject-chart.html
긴 목록에서 특정 학년이나 학기로 바로 이동할 수 있는 네비게이션을 추가
> 페이지 네비게이션 추가

- index.html
> index.html에 필요 없는 input 버튼 제거했습니다. 

- css/style.css
- index.html
style.css에 index.html의 코드가 들어가 있던 것을 삭제하고, index.html에 있는 버튼에 bnt 클래스를 만들어 적용했습니다
bnt 클래스는 배경 색상과 radius를 설정했습니다
> style.css에 불필요한 코드 삭제와 index.html 에서 버튼의 디자인 수정

- json creator/creator main.js
- json creator/json creator.html
- json creator/style.css
크게 보면 전공자가 아니더라도 파일을 만들어 data 파일에 넣기만하면 년도가 바뀌어도 지속적으로 수정 가능하게 해야한다고 생각해서 만든 사이드 프로젝트입니다.
add Entry로 추가
Generate JSON로 다운로드
File name 파일이름 입력
밑에는 해당 형식으로 바꾸어 주는걸 출력함. (처음에는 작은칸인데 확장가능)
> courses.json형식의 json파일을 만들어주는 프로그램 추가

- index.html
> index.html 오타 수정

- Show.html
show의 검색기능을 업데이트 하여 스페이스의 위치가 달라도 위치를 찾아낼 수 있습니다.
저번 pr에서 충돌이 일어나서 다시 보냅니다.
> Show.html에서 검색기능을 업데이트 했습니다.

- subject-chart.html
#57 이슈 해결
상단에 png로 저장 버튼을 만들어 png파일로 저장할수 있도록 만들었습니다.
> 과목이수체계도 png파일로 저장할 수 있도록 만들었습니다.

- subject-chart.html
#160
doSearch 함수를 수정하였습니다.
"프로그래밍"을 검색하면 "고급프로그래밍", "파이썬 프로그래밍" 등 프로그래밍이 포함된 단어를 검색합니다.
> 검색 기능을 수정하였습니다.

- subject-chart.html
show.html 파일에서 search.css 파일의 경로를 /css/search.css에서 ./css/search.css로 수정하였습니다.
> search.css 파일의 경로 수정

- subject-chart.html
> subject-chart.html에서  279번째 줄에  </script>이게 빠져서 실행이안되는 문제 해결

- js/subject-chart-module.js
검색에 대한 기능이 계속 추가되어왔는데
이제 Subject-chart.html에서 띄어쓰기를 무시하면서 중간단어만 검색해도 검색이 됩니다.
"웹스크립트 프로그래밍" 을 "웹스크립트프로그래밍" 이라 검색해도 나오고
"네트워크 프로그래밍 및 보안"을 "프로그래밍및보안"이라고 검색해도 나옵니다
> 띄어쓰기와 중간단어를 이용한 검색

- js/subject-chart-module.js
#209에서 js파일이 생겨서 충돌이 생겼는데 js디렉터리로 옮겨서 충돌 해결했습니다.
> #209 충돌 문제 해결

- Show.html
> svg 크기를 설정했습니다

- js/subject-chart-module.js
- subject-chart.html
다른 학년을 클릭하면 해당 학년에 맞는 학과만 나타납니다.
>  1234학년 버튼 기능을 추가했습니다.

- subject-chart.html
> subject-chart.html css 경로 수정

- js/show.js
현재 그래프 파일을 집어넣으면 이전 파일이 그대로 남아있는 버그를 수정했습니다.
> show.js 그래프 그리기전 이전 그래프를 제거합니다

- subject-chart.html
subject-chart가 subject-chart-module보다 먼저 로드되도록 변경했습니다.
> subject-chart.html 의 로드 순서 변경

- Show.html
> Show.html 의 메타데이터 변경

- js/show.js
링크에 마우스를 올렸을 때 트랙명을 보여주도록 mouseover 이벤트를 추가
> show.js 과목을 연결하는 선에 마우스를 올렸을 때 트랙명이 보이도록 수정

- css/style.css
style.css import 구문을 제거하고, HTML의 <head> 섹션에 <link> 태그를 추가를해서 css폰트 임포트 최적화를 하였습니다.
> CSS 폰트 임포트 최적화

- subject-chart.html
[모든버튼 활성화 비활성화 버튼 생성](https://github.com/oss2024hnu/coursegraph-js/commit/ee763d27d72b8b1b1b630ec5636d73fd6b6482cb)
> 모든버튼 활성화 비활성화 버튼 생성 

- css/style.css
CSS 미디어 쿼리를 사용하여 반응형 디자인을 구현해서 다양한 화면 크기와 해상도에서 웹사이트의 접근성과 가독성을 높였습니다.
> style.css 반응형 디자인

- js/subject-chart-module.js
각 학년 버튼을 눌렀을 때, 선택한 학년을 제외한 다른 학년의 시스템도는 모두 투명 상태로 변합니다.
> 1234학년 버튼 기능 향상.

- js/search.js
과목명뿐만 아니라 교수명, 트랙, 학점 등 다양한 필터를 적용할 수 있는 검색 기능을 추가하여 사용자가 필요한 정보를 빠르게 찾을 수 있도록 해보았습니다. search.js 파일을 새로 만들어서 추가하고, Show.html 코드 수정했습니다.
> search.js, Show.html 검색 기능 추가

- subject-chart.html
#308 
모든 과목 활성화, 비활성화 버튼이 하나 더 생긴 문제를 해결했습니다.
> #308 문제 해결

- subject-chart.html
#305
다크모드시 글자가 하얗게 보여 가시성이 좋지 않아
주변 배경색을 고려해 검정색으로 고정해놓았습니다.
#308 
기존 존재하는 작동하지 않거나 같은 기능을 하는 버튼을 제거했습니다
> #305 다크모드에서의 가시성 개선

- css/subject-chart.css
#327
박스 사이즈 조절을 통해 글자가 올바르게 표시 되도록 수정하였습니다
> #327 공통권장항목 박스 css수정

- subject-chart.html
> 최신버전 문제 해결
